/*** 
* Class: Account_Update_SALClassificationTest
* Description: Unit test for Account_Update_SALClassificationTest
* Author: Elmar Chen
* Create Time: 06/18/2015 13:52:26
*
**********************************************************************
*
*   Date            Author                 Change
*   06/18/15        Elmar Chen             Initial Creation                          
*
*
*********************************************************************/

@isTest
private class Account_Update_SALClassificationTest {
/*
	@isTest static void test_Account_Update_SALClassificationTest() {


		List<Decimal> revs = new List<Decimal>{
				4000000000.00, 5000000000.00, 400000000.00, 500000000.00, 50000000.00
		};
		Test.startTest();
		List<Account> acts = TestDataFactory.createAccounts(revs.size(), true, new Map<String, Object>{
				'AnnualRevenue' => revs
		});
		Test.stopTest();
		acts = [SELECT SAL_Classification__c FROM Account ORDER BY NAME];
		System.assertEquals(acts[0].SAL_Classification__c, 'Strategic');
		System.assertEquals(acts[1].SAL_Classification__c, 'Strategic');
		System.assertEquals(acts[2].SAL_Classification__c, 'Enterprise');
		System.assertEquals(acts[3].SAL_Classification__c, 'Enterprise');
		System.assertEquals(acts[4].SAL_Classification__c, 'Commercial');
	}
*/
}